name: SQL Analysis
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze:
    uses: ./.github/workflows/sql-pr-analysis.yml
    with:
      migrations_path: db/migrations
    secrets:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}