name: SQL Analysis
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze:
    uses: y-infoblox/sql-optimizer-agent/.github/workflows/sql-pr-analysis.yml@st_setup
    with:
      migrations_path: db/migrations
    secrets:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}